services:
    PoP\LocationPosts\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\LocationPosts\TypeResolverPickers\:
        resource: '../src/TypeResolverPickers/*'
        public: true
