services:
    PoP\LocationPosts\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\LocationPosts\TypeResolverPickers\:
        resource: '../src/TypeResolverPickers/*'
        public: true

    PoP\LocationPosts\TypeResolvers\:
        resource: '../src/TypeResolvers/*'
        public: true

    PoP\LocationPosts\Conditional\Users\FieldResolvers\:
        resource: '../src/Conditional/Users/FieldResolvers/*'
        public: true

    PoP\LocationPosts\Conditional\Taxonomies\FieldResolvers\:
        resource: '../src/Conditional/Taxonomies/FieldResolvers/*'
        public: true
